export const mixes = [
    {
    "id":"afrobeat-vol5-mix",
    "title":"Afrobeat Vol5 Mix",
    "date":2023,
    "mix_likes":178,
    "download_url":"https://hearthis.at/dj-kabadi254/dj-kabadi-afrobeats-vol5-mix-2023/download/?secret=wJoi3",
    "period":"latest",
    // "description":,
    "category":"",
    "image_url":"https://github.com/djkabadi/images/blob/main/AFROBEAT%205.jpg?raw=true"
  },
    
    {
        "id":"bongo-mixtape-2023" ,
        "title": "Bongo Mixtape 2023 by DJ Kabadi",
        "date": 2023,
        "mix_likes":1635,
        "youtube_url":"",
        "download_url":"https://www.mediafire.com/file/gu10g2m6lq35wnr/DJ_KABADI_-_BONGO_MIX_2023%255B1%255D.mp3/file",
        "period":"latest",
        "description": [
           " 1.Intro",
            " 2.Nakuja by Tommy Flavour Ft Marioo",
            " 3.Sawa by Jay Melody",
            " 4.Nakupenda by Jay Melody",
            " 5.Yatapita by Diamond Platnumz",
            " 6.Nitasema by Jay Melody",
           " 7.Kioo by Harmonize ft Angella",
           " 8.You by Bruce Africa",
           " 9.Bembeleze by Willy Paul ft Nandy",
           " 10.Pele pele by Rayvanny ft Luana Vjollca",
           " 11.I Wish by Kusah",
            " 12.Sugar Rmx by Jay Melody ft MArioo",
            " 13.Utu by Alikiba",
            " 14.No body by Darassa ft Bien",
            " 15.Mdomo by Harmonize ft Ibraah",
            " 16.Jugni by Diljit Dosanjh ft Diamond Platnumz",
            " 17.Senorita by Rayvanny ft Gims",
            " 18.Huyu HApa by Mbosso",
            " 19.Mtaalam by Mbosso",
            " 20.Baikoko by Mbosso ft Diamond Platnumz",
            " 21.Zuwena by Diamond Platnumz",
            " 22.Yuda by Nandy",
            " 23.Lalala by Alikiba ft K2ga, Vanillah, Abdukiba, Tommy Flavour",
            " 24.Gidi by Diamond Platnumz",
            " 25.Zeze by Jay Melody",
            " 26.Nisamehe by Barakah the Prince ft Alikiba",
        ],
         "category": "",
         "image_url":"https://github.com/djkabadi/images/blob/main/BONGO%20MIX%20C.jpg?raw=true"
      },
    {
        "id":"the-billion-experience-mix" ,
        "title": "the billion experience mix (ft Dj Ocheezy)",
        "date": 2022,
        "mix_likes":123,
        "youtube_url":"",
        "download_url":"https://download1320.mediafire.com/11e7t398lozg/klwbi349jak63f5/THE+BILLIONS+EXPERIENCE+MIX+VOL1+BY+DJ+KABADI+X+DJ+OCHEEZY.mp3",
        "period":"latest",
        "description":"",
         "category": "",
         "image_url":"https://github.com/djkabadi/images/blob/main/GREATEST%20MIX1.jpg?raw=true"
      },
    {
        "id":"afrobeat-mix-vol-3" ,
        "title": "afrobeat mix vol 3",
        "date": 2022,
        "mix_likes":322,
        "youtube_url":"",
        "period":"latest",
        "download_url":"https://download1082.mediafire.com/zoqlv2qml9pg/f0aoajrc8fza486/DJ+KABADI+-+AFROBEAT+MIX+VOL3.mp3",
        "description": "",
         "category": "",
         "image_url":"https://github.com/stancillous/e-images/blob/main/AFROBT3.jpg?raw=true"
      },
    {
        "id":"kenyan-drill-mix" ,
        "title": "kenyan drill mixtape",
        "date": 2022,
        "mix_likes":78,
        "download_url":"https://download1980.mediafire.com/kiqwscvy12hg/0iutk72whlsvhqq/DJ+KABADI+-+KENYAN+DRILL+MIX+2022++Buruklyn+Boyz%2C+Wakadinali%2C+GTA+Tv.mp3",
        "period":"latest",
        "description": [
           " 1.Woosh by Mr Right {Buruklyn Boyz}",
           " 2.Charged Up by Mando x Natty",
           " 3.Dream ya Kutoka Kwa Block by Buruklyn Boyz",
           " 4.Blanda by Ghetto Champs ft Rudra Kartel",
           " 5.Avoid Those People by Wakadinali ft All Stars",
            "6.Love Song by Wakadinali",
           " 7.Wild by Buruklyn Boyz, Ajay",
           " 8.Step by Smurph k27 ft Chana 4 Prez",
           " 9.Nairobi by Buruklyn Boyz",
            "10.Mtoto ni Mrembo by Wakadinali",
           " 11.Corns Freestyle by Buruklyn Boyz, Ajay",
            "12.Mrenga by Wakadinali",
           "13.Ki Dejavu by Mr Right, Ajay, Davaji, Ksplash",
            "14.Billie Jean by Buruklyn Boyz",
           " 15.Location 58 by Buruklyn Boyz",
           " 16.Piga Lean by Buruklyn Boyz",
           " 17.Extra Pressure by Wakadinali",
           " 18.Nairobbery by PRXNCE",
           " 19.Iraq by Natty",
           " 20.2 Faced by Yammy Gang ft YS 28th",
           " 21.NyaraNyara by Wakadinali",
           " 22.Morio Anzenza by Wakadinali ft Dyana Cods",
            "23.Mbona by Boutross",
            "24.Fine Settings by Trio Mio",
            "25.Umoroto by Wakadinali",
        ],
        "category": "",
        "image_url":"https://github.com/djkabadi/images/blob/main/drill.jpg?raw=true"
      },
    {
        "id":"afrobeats-vol-4" ,
        "title": "afrobeats vol 4",
        "date": 2022,
        "mix_likes":56,
        "youtube_url":"",
        "download_url":"https://download1338.mediafire.com/wlpkvdh67zqg/n94ko89gh0jjv8n/DJ+KABADI-AFROBEATS+VOL4+MIX.mp3",
        "period":"latest",
        "description":"",        "category": "",
         "image_url":"https://github.com/stancillous/e-images/blob/main/AFROBEAT%204.jpg?raw=true"
      },
    {
        "id": "the-addiction-mix",
        "title": "the addiction mix",
        "date": 2022,
        "period":"popular",
        "description": "",
        "download_url":"https://download1492.mediafire.com/4wxpjzp68etg/0nxr6fm85xj0ezb/THE+ADDICTION+MIX+1+%5BAMAPIANO+EDITION%5D+-+DJ+KABADI.mp3",
        "category": "",
        "mix_likes":324,
        "image_url":"https://github.com/djkabadi/images/blob/main/ADDICTION%201%20AMAPIANO.jpg?raw=true"
      },
      {
        "id":"pop-sparkle-vol-2-mix",
        "title":"pop sparkle vol 2-mix",
        "date":2020,
        "mix_likes":99,
        "youtube_url":"",
        "download_url":"https://download937.mediafire.com/d1nmujvhvcjg/9sx2wwwe0h3al5j/DJ+KABADI+-+POP+SPARKLE+VOL+2+MIX.mp3",
        "period":"popular",
        "description": "",        
         "category":"",
         "image_url":"https://github.com/djkabadi/images/blob/main/POP%20SPARKLE2.jpg?raw=true"
      },
      {
        "id":"hiphop-epidemix-vol-3-mix",
        "title":"hiphop epidemix vol 3",
        "date":2023,
        "mix_likes":121,
        "youtube_url":"",
        "download_url":"https://download1502.mediafire.com/kpkfe85p68kg/4xwm31mtuei392j/HIPHOP+EPIDEMIX+VOL+3+BY+DJ+KABADI.mp3",
        "period":"popular",
        "description": "",
         "category":"",
         "image_url":"https://github.com/djkabadi/images/blob/main/epidemix3.jpg?raw=true"
      },
      {
        "id":"country-music-mix",
        "title":"country music mix",
        "date":2019,
        "mix_likes":78,
        "youtube_url":"",
        "download_url":"",
        "period":"popular",
        "description": "",        
         "category":"",
         "image_url":"https://github.com/djkabadi/images/blob/main/cm1.jpg?raw=true"
      },
      {
        "id":"best-of-69",
        "title":"69 mixtape",
        "date":2023,
        "mix_likes":129,
        "download_url":"https://download1335.mediafire.com/7svnpevcdl0g/ye3rrx61lu43iwm/69+MIXTAPE+BY+DJ+KABADI.mp3",
        "period":"latest",
        "description":"",
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/69.jpg?raw=true"
      },
      {
        "id":"trap-agenda-4",
        "title":"trap agenda vol 4",
        "date":2023,
        "mix_likes":217,
        "download_url":"https://download1521.mediafire.com/evpqqh6fntlg/8gicaad541wzcjb/DJ+KABADI+-+TRAP+AGENDA+VOL+4+MIX.mp3",
        "period":"latest",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/AGENDA%204%20A.jpg?raw=true"
      },
      {
        "id":"hiphop-epidemix-vol-4",
        "title":"hiphop epidemix vol 4 ",
        "date":2023,
        "mix_likes":183,
        "download_url":"https://download1337.mediafire.com/9385svx7zkmg/xk3snfjxldjzroj/HIP+HOP+EPIDEMIX+VOL+4+BY+DJ+KABADI.mp3",
        "period":"popular",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/EPIDEMIX%204.jpg?raw=true"
      },
      {
        "id":"gengetone-vol-5-mix",
        "title":"gengetone vol 5 mix",
        "date":2023,
        "mix_likes":321,
        "download_url":"https://download1074.mediafire.com/zr7imhitb7mg/h9t9ybr29b31pif/DJ+KABADI+-+GENGETONE+VOL+5.mp3",
        "period":"latest",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/GTONE%205.jpg?raw=true"
      },
      {
        "id":"gengetone-vol-6-mix",
        "title":"gengetone vol 6 mix",
        "date":2023,
        "mix_likes":311,
        "download_url":"",
        "period":"popular",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/GTONE%206.jpg?raw=true"
      },
      {
        "id":"mbogi-genje-mixtape",
        "title":"mbogi genje mixtape",
        "date":2023,
        "mix_likes":421,
        "download_url":"https://download1476.mediafire.com/i64z54e8kssg/nxeii4x03d6c0x6/DJ+KABADI+-+MBOGI+GENJE+MIX+2021.mp3",
        "period":"popular",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/MBOGI%20GENJE%20MIX.jpg?raw=true"
      },
      {
        "id":"reggae-relics-vol-1-mix",
        "title":"reggae relics vol 1 mix",
        "date":2023,
        "mix_likes":129,
        "download_url":"https://download1322.mediafire.com/26fytb7137ug/xsxxu0zq4vfntjs/DJ+KABADI+-+REGGAE+RELICS+VOL1+MIX.mp3",
        "period":"popular",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/REGGAE%20RELICS.jpg?raw=true"
      },
      {
        "id":"reggae-riddim-mix-vol-1",
        "title":"reggae riddim mixtape vol 1 (ft Dj Sonch)",
        "date":2023,
        "mix_likes":99,
        "download_url":"https://download1346.mediafire.com/394eovlchoog/i47efromkcmvwgr/REGGAE+RIDDIM+MIX+BY+DJ+KABADI+X+DJ+SONCH.mp3",
        "period":"latest",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/RR_2.jpg?raw=true"
      },
      {
        "id":"urban-gospel-vol-2-mix",
        "title":"urban gospel vol 2 mix",
        "date":2023,
        "mix_likes":99,
        "download_url":"https://download1080.mediafire.com/bdo12k50ppsg/8s89swrrjnu6udy/DJ+KABADI+-+URBAN+GOSPEL+VOL2+MIX.mp3",
        "period":"latest",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/URBAN%20G2.jpg?raw=true"
      },
      {
        "id":"valentine-affair-mixtape",
        "title":"valentine affair mixtape",
        "date":2023,
        "mix_likes":76,
        "download_url":"https://download1336.mediafire.com/eym0c9kfbqbg/2jdqulb6u4prxc0/DJ+KABADI+-+VALENTINES+AFFAIR+MIXTAPE+2022.mp3",
        "period":"latest",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/VALENTINE%20AFFAIR%20MIX.jpg?raw=true"
      },
      {
        "id":"the-wasafi-experience-mix",
        "title":"the wasafi experience mix (ft Dj Ocheezy)",
        "date":2023,
        "mix_likes":132,
        "download_url":"https://download1532.mediafire.com/zkb5ioke67qg/i7qvls4ggwsh5dc/WASAFI+MIXTAPE+2021+BY+DJ+KABADI+X+DJ+OCHEEZY.mp3",
        "period":"",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/WASAFI%20MIXTAPE.jpg?raw=true"
      },
      {
        "id":"blueface-mixtape",
        "title":"blueface mixtape ",
        "date":2023,
        "mix_likes":323,
        "download_url":"https://download843.mediafire.com/vfwir06j0xzg/vjq70dsks2ceja4/BLUEFACE+FULL++MIX++BY+DJ+KABADI+THE+BADDEST.mp3",
        "period":"",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/blueface.jpg?raw=true"
      },
      {
        "id":"crunk-it-up-mix",
        "title":"crunk it up mix vol 1",
        "date":2023,
        "mix_likes":832,
        "download_url":"https://download1651.mediafire.com/4uwea3itcvbg/kl16zaqh4px0el1/DJ+KABADI+CRUNK+IT+UP+MIX.mp3",
        "period":"popular",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/crunk1.jpg?raw=true"
      },
      {
        "id":"crunk-it-up-mix-vol-2",
        "title":"crunk it up mix vol 2",
        "date":2022,
        "mix_likes":352,
        "download_url":"https://download1651.mediafire.com/lk04ti9ihnag/q9bkolfugwa0fa2/CRUNK+IT+UP+MIX+VOL+2+BY+DJ+KABADI.mp3",
        "period":"latest",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/crunk2.jpg?raw=true"
      },
      {
        "id":"dancehall-heist-vol-3",
        "title":"dancehall heist vol 3 (ft Dj Mojoh)",
        "date":2023,
        "mix_likes":111,
        "download_url":"https://download1586.mediafire.com/sc2359dhj9ig/7symbas1ucqrvj8/DANCEHALL+HEIST+VOL3+MIX+BY+DJ+KABADI+FT+DJ+MOJOH.mp3",
        "period":"latest",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/dh3.jpg?raw=true"
      },
      {
        "id":"hiphop-epidemix-vol-5-mix",
        "title":"hiphop epidemix vol 5",
        "date":2023,
        "mix_likes":232,
        "download_url":"",
        "period":"latest",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/epidemix5.jpg?raw=true"
      },
      {
        "id":"ragga-charm-vol-2-mix",
        "title":"ragga charm mix vol 2",
        "date":2023,
        "mix_likes":45,
        "download_url":"https://download1323.mediafire.com/b8le0bjy27eg/9cm0lv0x2wo757g/RAGGA+CHARM+VOL2+MIX+BY+DJ+RYNES+X+DJ+KABADI.mp3",
        "period":"latest",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/ragga%20charm2.jpg?raw=true"
      },
      {
        "id":"street-mixtape-vol-4",
        "title":"street mixtape vol 4",
        "date":2022,
        "mix_likes":94,
        "download_url":"https://download1509.mediafire.com/8wsv0kqu2skg/n4tp8ukkfa611o2/DJ+KABADI+-+STREET+MIXTAPE+VOL4.mp3",
        "period":"",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/sm4.jpg?raw=true"
      },
      {
        "id":"the-soul'd-out-mixtape",
        "title":"the soul'd out mixtape",
        "date":2022,
        "mix_likes":224,
        "download_url":"https://download944.mediafire.com/8gjlpaivhl2g/r7hydb42kesamut/SOUL+D+OUT+MIXX+BY+DJ+KABADI.mp3",
        "period":"popular",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/sould%20out%201.jpg?raw=true"
      },
      {
        "id":"westlife-edition-mix-vol-2",
        "title":"rnb mixtape (westlife edition)",
        "date":2022,
        "mix_likes":179,
        "download_url":"https://download1591.mediafire.com/wiegcawnyyzg/q88r85fvqur2jra/RNB+VOL+2+WESTLIFE+EDITION+BY+DJ+KABADI.mp3",
        "period":"",
        // "description":,
        "category":"",
        "image_url":"https://github.com/djkabadi/images/blob/main/westlife.jpg?raw=true"
      },


]

export default defineEventHandler(async(event) =>{ 

 
  return mixes


  })
